#!/bin/sh
set -u

CHECK_URL="${CHECK_URL:-wss://myvv-ga6oanbk.b4a.run/chat}"
CHECK_INTERVAL_SECONDS="${CHECK_INTERVAL_SECONDS:-300}"
CHECK_TIMEOUT_SECONDS="${CHECK_TIMEOUT_SECONDS:-10}"
CHECK_RETRY_SECONDS="${CHECK_RETRY_SECONDS:-5}"
CHECK_PRINT_SUCCESS="${CHECK_PRINT_SUCCESS:-0}"
export CHECK_URL CHECK_INTERVAL_SECONDS CHECK_TIMEOUT_SECONDS CHECK_RETRY_SECONDS CHECK_PRINT_SUCCESS

exec python3 ./websocket-check.py
